package com.springboot.model2;

public class Clazz {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clazz.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clazz.clazz_name
     *
     * @mbggenerated
     */
    private String clazzName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clazz.clazz_age
     *
     * @mbggenerated
     */
    private String clazzAge;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clazz.id
     *
     * @return the value of clazz.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clazz.id
     *
     * @param id the value for clazz.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clazz.clazz_name
     *
     * @return the value of clazz.clazz_name
     *
     * @mbggenerated
     */
    public String getClazzName() {
        return clazzName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clazz.clazz_name
     *
     * @param clazzName the value for clazz.clazz_name
     *
     * @mbggenerated
     */
    public void setClazzName(String clazzName) {
        this.clazzName = clazzName == null ? null : clazzName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clazz.clazz_age
     *
     * @return the value of clazz.clazz_age
     *
     * @mbggenerated
     */
    public String getClazzAge() {
        return clazzAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clazz.clazz_age
     *
     * @param clazzAge the value for clazz.clazz_age
     *
     * @mbggenerated
     */
    public void setClazzAge(String clazzAge) {
        this.clazzAge = clazzAge == null ? null : clazzAge.trim();
    }

    @Override
    public String toString() {
        return "id" + id + " 班级：" + clazzName + " 年限：" + clazzAge;
    }
}