server:
  port: 8093
  context-path: /
datasource1:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/springboottest
  username: root
  password: 123
  type: com.zaxxer.hikari.HikariDataSource
datasource2:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/springboot
  username: root
  password: 123
  type: com.zaxxer.hikari.HikariDataSource


spring:
  aop:
    auto: true #
    proxy-target-class: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/mobile
      username: mobile
      password: mobilemk2018

#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  pageSizeZero: true
#  params: count=countSql
logging:
  level:
    com.springboot.mapper: DEBUG

