server:
  port: 8093
  context-path: /
spring:
  thymeleaf:
    prefix: classpath:/pages/
    cache: false
datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql:///springboottest
    userName: root
    password: root


